=== sanashahid819/xml/xml/externam.dtd
<?xml version="1.0" encoding="UTF-8"?>
    <!ELEMENT bio (students*,empolyee*)>
    <!ELEMENT students (name,age,qulification)>
    <!ELEMENT empolyee (name,age,qulification,salary)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT qulification (#PCDATA)>
    <!ELEMENT salary (#PCDATA)>
    <!ATTLIST name dtd2 CDATA #FIXED "aptech">

=== sanashahid819/xml/xml/external.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bio SYSTEM "externam.dtd"
[
<!ENTITY abc "121">
]
>

<bio>
    <students>
        <name dtd2="aptech">&abc;ali</name>
        <age>22</age>
        <qulification>MBA</qulification>
    </students>


    <empolyee>
        <name>ali</name>
        <age>22</age>
        <qulification>MBA</qulification>
        <salary>70000</salary>
    </empolyee>

</bio>
